# Generated by Django 2.1.4 on 2019-03-09 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classsession',
            name='session',
            field=models.CharField(default='', max_length=500),
        ),
    ]
