# Generated by Django 2.1.4 on 2019-03-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190309_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='session',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='session',
            field=models.ManyToManyField(blank=True, to='accounts.ClassSession'),
        ),
    ]
