# Generated by Django 2.1.4 on 2019-03-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190309_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
