# Generated by Django 2.1.4 on 2019-03-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_classsession_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsession',
            name='slug',
        ),
    ]
