# Generated by Django 2.1.4 on 2019-03-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_classsession_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
