# Generated by Django 2.1.4 on 2019-03-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190312_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='classsession',
            name='course_code',
            field=models.ManyToManyField(blank=True, to='accounts.CourseCode'),
        ),
    ]
