# Generated by Django 2.1.4 on 2019-03-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190313_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classsession',
            name='course_code',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='course_code',
            field=models.ManyToManyField(blank=True, to='accounts.CourseCode'),
        ),
    ]
