# Generated by Django 2.1.4 on 2019-03-15 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190315_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='course_code',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='course_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.CourseCode'),
        ),
    ]
