# Generated by Django 2.1.4 on 2019-03-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20190315_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='course_code',
        ),
    ]
