# Generated by Django 2.1.4 on 2019-03-15 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_userprofile_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecode',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.UserProfile'),
        ),
    ]
