# Generated by Django 2.1.4 on 2019-03-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_coursecode_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecode',
            name='session',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
