# Generated by Django 2.1.4 on 2019-03-15 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_coursecode_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecode',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ClassSession'),
        ),
    ]
