# Generated by Django 2.1.4 on 2019-03-16 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20190315_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursecode',
            old_name='teacher',
            new_name='teacher1',
        ),
        migrations.AddField(
            model_name='coursecode',
            name='teacher2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coursecode_requests_created', to='accounts.UserProfile'),
        ),
    ]
