# Generated by Django 2.1.4 on 2019-03-16 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20190316_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecode',
            name='teacher1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursecode',
            name='teacher2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher2', to=settings.AUTH_USER_MODEL),
        ),
    ]
