# Generated by Django 2.1.4 on 2019-05-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_studentprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='student_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_username',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
