# Generated by Django 2.1.4 on 2019-05-16 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0018_auto_20190515_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_roll',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_session',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_username',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='students/image'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='session',
            field=models.ManyToManyField(blank=True, to='accounts.ClassSession'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
