# Generated by Django 2.1.4 on 2019-05-18 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20190518_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_session',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='student_session',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
