# Generated by Django 2.1.4 on 2019-05-18 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20190518_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='teacher_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
