# Generated by Django 2.1.4 on 2019-05-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20190518_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='teacher_position',
            field=models.CharField(choices=[(1, 'Lecturer'), (2, 'Asistant Professor'), (3, 'Associate Professor'), (4, 'Professor')], max_length=1),
        ),
    ]
