# Generated by Django 2.1.4 on 2019-05-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_auto_20190518_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='teacher_username',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
