# Generated by Django 2.1.4 on 2019-05-19 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_teacherprofile_teacher_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='teacher_username',
        ),
    ]
