# Generated by Django 2.1.4 on 2019-05-21 11:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_teacherprofile_teacher_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_url', models.UUIDField(default=uuid.uuid4)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.ClassSession')),
            ],
        ),
    ]
