# Generated by Django 2.1.4 on 2019-05-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_uniquelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='uniquelink',
            name='select_course_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/image'),
        ),
        migrations.AlterField(
            model_name='classsession',
            name='session',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='uniquelink',
            name='random_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='uniquelink',
            name='session',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
