# Generated by Django 2.1.4 on 2019-05-21 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20190521_1941'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UniqueLink',
            new_name='PresentSheet',
        ),
        migrations.RenameField(
            model_name='presentsheet',
            old_name='session',
            new_name='select_session',
        ),
    ]
