# Generated by Django 2.1.4 on 2019-05-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20190521_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentsheet',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
