# Generated by Django 2.1.4 on 2019-05-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_presentsheet_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentsheet',
            name='attend_user',
            field=models.ManyToManyField(to='accounts.StudentProfile'),
        ),
    ]
