# Generated by Django 2.1.4 on 2019-05-26 18:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_presentsheet_attend_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentsheet',
            name='attend_user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
