# Generated by Django 2.1.4 on 2019-05-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_auto_20190527_0059'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user_type',
            field=models.CharField(default='student', max_length=20),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='user_type',
            field=models.CharField(default='teacher', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='teacher_position',
            field=models.CharField(choices=[(1, 'Lecturer'), (2, 'Asistant Professor'), (3, 'Associate Professor'), (4, 'Professor')], max_length=20),
        ),
    ]
