# Generated by Django 2.1.4 on 2019-05-27 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20190527_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherPresentSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.TeacherProfile')),
            ],
        ),
    ]
