# Generated by Django 2.1.4 on 2019-05-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_teacherpresentsheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherpresentsheet',
            name='teacher_user',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='class_presentsheet',
            field=models.ManyToManyField(to='accounts.PresentSheet'),
        ),
        migrations.DeleteModel(
            name='TeacherPresentSheet',
        ),
    ]
