# Generated by Django 2.0 on 2019-05-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20190530_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.IntegerField(),
        ),
    ]
