# Generated by Django 2.0 on 2019-05-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20190531_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
