# Generated by Django 2.0 on 2019-06-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20190531_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='user_type',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(blank=True, choices=[(1, 'Teacher'), (2, 'Student')], max_length=20),
        ),
    ]
