# Generated by Django 2.0 on 2019-06-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_auto_20190601_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_type',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='user_type',
            field=models.CharField(default='teacher', max_length=20),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='user_type',
            field=models.CharField(default='teacher', max_length=20),
        ),
    ]
