# Generated by Django 2.0 on 2019-06-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20190601_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='user_type',
            field=models.CharField(default='student', max_length=20),
        ),
    ]
