# Generated by Django 2.0 on 2019-06-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_auto_20190601_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='student_roll',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
