# Generated by Django 2.0 on 2019-06-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20190602_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_roll',
            field=models.IntegerField(default=None),
        ),
    ]
