# Generated by Django 2.0 on 2019-06-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_coursepercentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepercentage',
            name='percentage',
            field=models.IntegerField(null=True),
        ),
    ]
