# Generated by Django 2.0 on 2019-06-10 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_auto_20190610_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepercentage',
            name='teacher_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.TeacherProfile'),
        ),
    ]
