# Generated by Django 2.0 on 2019-06-12 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_auto_20190611_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepercentage',
            name='course_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.CourseCode'),
        ),
        migrations.AlterField(
            model_name='coursepercentage',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.ClassSession'),
        ),
    ]
