# Generated by Django 2.0 on 2019-06-12 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_auto_20190612_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecode',
            name='teacher1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursecode',
            name='teacher2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher2', to=settings.AUTH_USER_MODEL),
        ),
    ]
