# Generated by Django 2.0.1 on 2020-04-22 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepercentage',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
