# Generated by Django 2.0.1 on 2020-04-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200422_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursepercentage',
            old_name='student_user',
            new_name='student',
        ),
    ]
