# Generated by Django 2.0.1 on 2020-04-22 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200422_1613'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepercentage',
            name='student',
        ),
        migrations.RemoveField(
            model_name='coursepercentage',
            name='student_course',
        ),
        migrations.RemoveField(
            model_name='coursepercentage',
            name='student_session',
        ),
        migrations.RemoveField(
            model_name='coursepercentage',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='CoursePercentage',
        ),
    ]
