# Generated by Django 2.0.1 on 2020-04-22 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_check'),
    ]

    operations = [
        migrations.DeleteModel(
            name='check',
        ),
        migrations.RenameField(
            model_name='coursepercentage',
            old_name='student_course',
            new_name='course_code',
        ),
        migrations.RenameField(
            model_name='coursepercentage',
            old_name='student_session',
            new_name='session',
        ),
        migrations.RenameField(
            model_name='coursepercentage',
            old_name='student',
            new_name='student_user',
        ),
        migrations.RemoveField(
            model_name='coursepercentage',
            name='teacher',
        ),
        migrations.AddField(
            model_name='coursepercentage',
            name='teacher_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.TeacherProfile'),
        ),
        migrations.AlterField(
            model_name='coursepercentage',
            name='percentage',
            field=models.IntegerField(null=True),
        ),
    ]
